registration-service:
  environment: 'prod'
  replicas: 3
  verification:
    enabled: 'true'
    excluded-email-domains: 'redhat.com'
  auth-client:
    library-url: 'https://sso.redhat.com/auth/js/keycloak.js'
    config-raw: '{
                  "realm": "redhat-external",
                  "auth-server-url": "https://sso.redhat.com/auth",
                  "ssl-required": "none",
                  "resource": "crtoolchain-public",
                  "clientId": "crtoolchain-public",
                  "public-client": true
                }'
    public-keys-url: 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs'
  twilio:
    from-number: '+14158513935'
host-operator:
  secret:
    name: host-operator-secret
  config-map:
    name: host-operator-config
