apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "toolchain.dev.openshift.com/v1alpha1",
          "kind": "MasterUserRecord",
          "metadata": {
            "name": "johnsmith"
          },
          "spec": {
            "userAccounts": [
              {
                "spec": {
                  "nsLimit": "admin",
                  "nsTemplateSet": {
                    "namespaces": [
                      {
                        "revision": "abcdef",
                        "type": "ide"
                      },
                      {
                        "revision": "1d2f3q",
                        "type": "cicd"
                      },
                      {
                        "revision": "a34r57",
                        "type": "stage"
                      },
                      {
                        "revision": "ra24qw",
                        "type": "default"
                      }
                    ],
                    "tierName": "basic"
                  },
                  "userID": "1a03ecac-7c0b-44fc-b66d-12dd7fb21c40"
                },
                "syncIndex": "135540409",
                "targetCluster": "east-2a"
              }
            ],
            "userID": "1a03ecac-7c0b-44fc-b66d-12dd7fb21c40"
          }
        },
        {
          "apiVersion": "toolchain.dev.openshift.com/v1alpha1",
          "kind": "NSTemplateTier",
          "metadata": {
            "name": "basic"
          },
          "spec": {
            "namespaces": [
              {
                "revision": "abcdef",
                "template": "{\"apiVersion\":\"v1\",\"kind\":\"Template\",\"metadata\":{\"name\":\"ide-template\"},\"objects\":{\"apiVersion\":\"v1\",\"kind\":\"ProjectRequest\",\"metadata\":{\"name\":\"$USERNAME-ide\"}}}\n",
                "type": "ide"
              },
              {
                "revision": "1d2f3q",
                "template": "{\"apiVersion\":\"v1\",\"kind\":\"Template\",\"metadata\":{\"name\":\"cicd-template\"},\"objects\":{\"apiVersion\":\"v1\",\"kind\":\"ProjectRequest\",\"metadata\":{\"name\":\"$USERNAME-cicd\"}}}\n",
                "type": "cicd"
              },
              {
                "revision": "a34r57",
                "template": "{\"apiVersion\":\"v1\",\"kind\":\"Template\",\"metadata\":{\"name\":\"stage-template\"},\"objects\":{\"apiVersion\":\"v1\",\"kind\":\"ProjectRequest\",\"metadata\":{\"name\":\"$USERNAME-stage\"}}}\n",
                "type": "stage"
              },
              {
                "revision": "ra24qw",
                "template": "{\"apiVersion\":\"v1\",\"kind\":\"Template\",\"metadata\":{\"name\":\"default-template\"},\"objects\":{\"apiVersion\":\"v1\",\"kind\":\"ProjectRequest\",\"metadata\":{\"name\":\"$USERNAME\"}}}\n",
                "type": "default"
              }
            ]
          }
        },
        {
          "apiVersion": "toolchain.dev.openshift.com/v1alpha1",
          "kind": "RegistrationService",
          "metadata": {
            "labels": {
              "provider": "codeready-toolchain"
            },
            "name": "reg-service",
            "namespace": "toolchain-host-operator"
          },
          "spec": {
            "environment": "dev",
            "image": "quay.io/codeready-toolchain/registration-service:1574697457",
            "replicas": 4
          }
        },
        {
          "apiVersion": "toolchain.dev.openshift.com/v1alpha1",
          "kind": "UserSignup",
          "metadata": {
            "name": "1a03ecac-7c0b-44fc-b66d-12dd7fb21c40"
          },
          "spec": {
            "approved": true,
            "compliantUsername": "johnsmith-at-redhat-com",
            "targetCluster": "east-2a",
            "username": "johnsmith@redhat.com"
          }
        }
      ]
    capabilities: Basic Install
  name: toolchain-host-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MasterUserRecord keeps all information about user, user accounts
        and namespaces provisioned in CodeReady Toolchain SaaS system
      displayName: MasterUserRecord
      kind: MasterUserRecord
      name: masteruserrecords.toolchain.dev.openshift.com
      version: v1alpha1
    - description: NSTemplateTier configures user environment via templates used for
        namespaces the user has access to
      displayName: NSTemplateTier
      kind: NSTemplateTier
      name: nstemplatetiers.toolchain.dev.openshift.com
      version: v1alpha1
    - description: RegistrationService configures registration service deployment
      displayName: RegistrationService
      kind: RegistrationService
      name: registrationservices.toolchain.dev.openshift.com
      version: v1alpha1
    - description: UserSignup registres a user in the CodeReady Toolchain SaaS system
      displayName: UserSignup
      kind: UserSignup
      name: usersignups.toolchain.dev.openshift.com
      version: v1alpha1
  description: Placeholder description
  displayName: Host Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          - namespaces
          - componentstatuses
          - pods
          - services
          - bindings
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - create
          - list
          - watch
        - apiGroups:
          - template.openshift.io
          resources:
          - brokertemplateinstances
          - processedtemplates
          verbs:
          - get
          - list
        serviceAccountName: host-operator
      deployments:
      - name: host-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: host-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: host-operator
            spec:
              containers:
              - command:
                - host-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: host-operator
                image: REPLACE_IMAGE
                imagePullPolicy: IfNotPresent
                name: host-operator
                resources: {}
              serviceAccountName: host-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - podtemplates
          - resourcequotas
          - serviceaccounts
          - replicationcontrollers
          - limitranges
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - host-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - core.kubefed.io
          resources:
          - kubefedclusters
          verbs:
          - '*'
        - apiGroups:
          - core.kubefed.io
          resources:
          - kubefedclusters/status
          verbs:
          - update
        - apiGroups:
          - toolchain.dev.openshift.com
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          - authorization.openshift.io
          resources:
          - roles
          - rolebindings
          verbs:
          - '*'
        serviceAccountName: host-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
