apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    provider: codeready-toolchain
  name: advanced-dev
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      openshift.io/description: ${USERNAME}-dev
      openshift.io/display-name: ${USERNAME}-dev
      openshift.io/requester: ${USERNAME}
    labels:
      provider: codeready-toolchain
    name: ${USERNAME}-dev
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      provider: codeready-toolchain
    name: user-edit
    namespace: ${USERNAME}-dev
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: User
    name: ${USERNAME}
parameters:
- name: USERNAME
  required: true