apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: advanced-cluster-resources
objects:
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${USERNAME}
  spec:
    quota:
      hard:
        limits.cpu: 4000m
        limits.memory: 7Gi
        limits.ephemeral-storage: 5Gi
        requests.cpu: 1750m
        requests.memory: 7Gi
        requests.storage: 5Gi
        requests.ephemeral-storage: 5Gi
        persistentvolumeclaims: "2"
        pods: "100"
        replicationcontrollers: "100"
        services: "100"
        secrets: "100"
        configmaps: "100"
    selector:
      annotations:
        openshift.io/requester: ${USERNAME}
      labels: null
parameters:
- name: USERNAME
  required: true
