apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: advanced-cluster-resources
objects:
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${USERNAME}
  spec:
    quota:
      hard:
        limits.cpu: 10000m
        limits.memory: 7Gi
        limits.ephemeral-storage: 7Gi
        requests.cpu: 1750m
        requests.memory: 7Gi
        requests.storage: 15Gi
        requests.ephemeral-storage: 7Gi
        count/persistentvolumeclaims: "5"
        count/pods: "50"
        count/replicasets.apps: "30"
        count/replicationcontrollers: "30"
        count/deployments.apps: "30"
        count/deploymentconfigs.apps: "30"
        count/daemonsets.apps: "30"
        count/statefulsets.apps: "30"
        count/jobs.batch: "30"
        count/cronjobs.batch: "30"
        count/buildconfigs.build.openshift.io: "10"
        count/routes.route.openshift.io: "10"
        count/ingresses.extensions: "10"
        count/services: "10"
        count/secrets: "100"
        count/configmaps: "100"
    selector:
      annotations:
        openshift.io/requester: ${USERNAME}
      labels: null
parameters:
- name: USERNAME
  required: true
