apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: MasterUserRecord
metadata:
  name: johnsmith # username
spec:
  userID: 1a03ecac-7c0b-44fc-b66d-12dd7fb21c40
  userAccounts:
  - targetCluster: east-2a
    syncIndex: '135540409'
    spec:
      nsLimit: admin
      userID: 1a03ecac-7c0b-44fc-b66d-12dd7fb21c40
      nsTemplateSet:
        tierName: basic
        namespaces:
        - templateRef: basic-code-abcdef
        - templateRef: basic-dev-1d2f3q
        - templateRef: basic-stage-a34r57
        clusterResources:
        - templateRef: basic-clusterresources-a34r57
