apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: host-operator
  template:
    metadata:
      labels:
        name: host-operator
    spec:
      serviceAccountName: host-operator
      containers:
      - name: host-operator
        # Replace this with the built image name
        image: REPLACE_IMAGE
        command:
        - host-operator
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "host-operator"
