## Append samples you want in your CSV to this file as resources ##
resources:
- toolchain.dev.openshift.com_v1alpha1_usersignup.yaml
- toolchain.dev.openshift.com_v1alpha1_space.yaml
- toolchain.dev.openshift.com_v1alpha1_socialevent.yaml
# TODO
#+kubebuilder:scaffold:manifestskustomizesamples
