apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    toolchain.dev.openshift.com/provider: codeready-toolchain
  name: team-stage
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      openshift.io/description: ${USERNAME}-stage
      openshift.io/display-name: ${USERNAME}-stage
      openshift.io/requester: ${USERNAME}
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
    name: ${USERNAME}-stage
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
    name: rbac-edit
    namespace: ${USERNAME}-stage
  rules:
  - apiGroups:
    - authorization.openshift.io
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
    name: user-edit
    namespace: ${USERNAME}-stage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: User
    name: ${USERNAME}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
    name: user-rbac-edit
    namespace: ${USERNAME}-stage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rbac-edit
  subjects:
  - kind: User
    name: ${USERNAME}
- apiVersion: v1
  kind: LimitRange
  metadata:
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
    name: resource-limits
    namespace: ${USERNAME}-stage
  spec:
    limits:
    - type: "Container"
      default:
        cpu: 500m
        memory: 2Gi
      defaultRequest:
        cpu: 100m
        memory: 64Mi
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
    name: allow-same-namespace
    namespace: ${USERNAME}-stage
  spec:
    podSelector: {}
    ingress:
    - from:
      - podSelector: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
    name: allow-from-openshift-ingress
    namespace: ${USERNAME}-stage
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      toolchain.dev.openshift.com/provider: codeready-toolchain
    name: allow-from-openshift-monitoring
    namespace: ${USERNAME}-stage
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: monitoring
    podSelector: {}
    policyTypes:
    - Ingress
parameters:
- name: USERNAME
  required: true
