apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    toolchain.dev.openshift.com/provider: codeready-toolchain
  name: basic-cluster-resources
objects:
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    labels:
      provider: codeready-toolchain
    name: for-${USERNAME}
  spec:
    quota:
      hard:
        limits.cpu: 1750m
        limits.memory: 7Gi
        requests.storage: 5Gi
        persistentvolumeclaims: "2"
    selector:
      annotations:
        openshift.io/requester: ${USERNAME}
      labels: null
parameters:
- name: USERNAME
  required: true
