apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: basic-cluster-resources
objects:
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${USERNAME}
  spec:
    quota:
      hard:
        limits.cpu: 10000m
        limits.memory: 7Gi
        limits.ephemeral-storage: 7Gi
        requests.cpu: 1750m
        requests.memory: 7Gi
        requests.storage: 15Gi
        requests.ephemeral-storage: 7Gi
        count/pods: "30"
        count/replicasets.apps: "30"
    selector:
      annotations:
        openshift.io/requester: ${USERNAME}
      labels: null
- apiVersion: toolchain.dev.openshift.com/v1alpha1
  kind: Idler
  metadata:
    name: ${USERNAME}-dev
  spec:
    timeoutSeconds: 28800 # 8 hours
- apiVersion: toolchain.dev.openshift.com/v1alpha1
  kind: Idler
  metadata:
    name: ${USERNAME}-code
  spec:
    timeoutSeconds: 28800 # 8 hours
- apiVersion: toolchain.dev.openshift.com/v1alpha1
  kind: Idler
  metadata:
    name: ${USERNAME}-stage
  spec:
    timeoutSeconds: 28800 # 8 hours
parameters:
- name: USERNAME
  required: true
