kind: Template
apiVersion: v1
metadata:
  name: basic-tier
objects:
- kind: NSTemplateTier
  apiVersion: toolchain.dev.openshift.com/v1alpha1
  metadata:
    name: basic
    namespace: ${NAMESPACE}
  spec:
    clusterResources:
      templateRef: ${CLUSTER_TEMPL_REF}
    deactivationTimeoutDays: 1
    namespaces:
      - templateRef: ${CODE_TEMPL_REF}
      - templateRef: ${DEV_TEMPL_REF}
      - templateRef: ${STAGE_TEMPL_REF}
parameters:
- name: NAMESPACE
- name: CLUSTER_TEMPL_REF
- name: CODE_TEMPL_REF
- name: DEV_TEMPL_REF
- name: STAGE_TEMPL_REF
