apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: base1ns-cluster-resources
objects:
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-deployments
  spec:
    quota:
      hard:
        count/deployments.apps: "30"
        count/deploymentconfigs.apps: "30"
        count/pods: "50"
    selector:
      annotations: null
      labels:
        toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-replicas
  spec:
    quota:
      hard:
        count/replicasets.apps: "30"
        count/replicationcontrollers: "30"
    selector:
      annotations: null
      labels:
        toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-routes
  spec:
    quota:
      hard:
        count/ingresses.extensions: "30"
        count/routes.route.openshift.io: "30"
    selector:
      annotations: null
      labels:
        toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-jobs
  spec:
    quota:
      hard:
        count/jobs.batch: "30"
        count/daemonsets.apps: "30"
        count/cronjobs.batch: "30"
        count/statefulsets.apps: "30"
    selector:
      annotations: null
      labels:
        toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-services
  spec:
    quota:
      hard:
        count/services: "30"
    selector:
      annotations: null
      labels:
        toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-bc
  spec:
    quota:
      hard:
        count/buildconfigs.build.openshift.io: "30"
    selector:
      annotations: null
      labels:
        toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-secrets
  spec:
    quota:
      hard:
        count/secrets: "100"
    selector:
      annotations: null
      labels:
        toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: quota.openshift.io/v1
  kind: ClusterResourceQuota
  metadata:
    name: for-${SPACE_NAME}-cm
  spec:
    quota:
      hard:
        count/configmaps: "100"
    selector:
      annotations: null
      labels:
        toolchain.dev.openshift.com/space: ${SPACE_NAME}
- apiVersion: toolchain.dev.openshift.com/v1alpha1
  kind: Idler
  metadata:
    name: ${SPACE_NAME}-dev
  spec:
    timeoutSeconds: ${{IDLER_TIMEOUT_SECONDS}}
parameters:
- name: SPACE_NAME
  required: true
- name: IDLER_TIMEOUT_SECONDS
  # 12 hours
  value: "43200"

