apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: base1ns-tier
objects:
- kind: NSTemplateTier
  apiVersion: toolchain.dev.openshift.com/v1alpha1
  metadata:
    name: base1ns
    namespace: ${NAMESPACE}
  spec:
    clusterResources:
      templateRef: ${CLUSTER_TEMPL_REF}
    deactivationTimeoutDays: ${{DEACTIVATION_TIMEOUT_DAYS}}
    namespaces:
      - templateRef: ${DEV_TEMPL_REF}
parameters:
- name: NAMESPACE
- name: CLUSTER_TEMPL_REF
- name: DEV_TEMPL_REF
- name: DEACTIVATION_TIMEOUT_DAYS
  value: "30"
